<h1><b>Numpy</b></h1>
<hr>

<h3><b>개요</b></h3>
<p>
이번의 목표는 NumPy의 실제 사용방법을 이해하는 것 입니다. NumPy는 Python 데이터 분석 패키지 입니다.<br>
NumPy로 워크플로우 속도 향샹, scikit-learn과 같은 Numpy내부 패키지와 연동 할 수 있습니다.<br>
NumPy는 2000년 중반에 개발 되었으며, Numeric이라는 더 오래된 패키지에서 파생되었습니다.<br>
그리고 지금은 데이터 분석, 머신러닝과 같은 분야에 대부분 NumPy를 이용하고 있습니다.
</p>
<hr>

<h3><b>역할<b></h3>
<p>여기서 NumPy 라이브러리를 직접 사용해 보고, 데이터 배열을 생성하고, 슬라이싱하고, 조작하는 기본 원리를 배워봅시다.</p>
<hr>

<h3><b>목표<b></h3>
<p>Python에서 수치형 데이터를 효율적으로 조작, 분석하고 통찰력을 추출하기 위한 기본적인 NumPy 연산과 기술을 익힙니다.</p>
<hr>

<h3><b>가상환경 설정하기<b></h3>
<ol>
    <li>python 3.X</li>
    <li>NumPy</li>
    <li>Jupyter or Jupyterlab</li>
</ol>
<hr>

<b>아래 버튼 눌러서 가상환경 생성 영상 ⬇️ </b><br>
[가상환경 만들기](https://example.com)

In [1]:
# numpy 불러오기
import numpy as np

<h2><b>연습1:</b> 첫 번째 NumPy 배열</h2>

문제: integeran , a float, a, a string, a dictionary, a list, tuplea, seta 를 포함하는 NumPy 배열을 만듭니다 boolean. Python 파일 끝이나 Jupyter Notebook 셀에 다음 코드를 추가합니다.

In [2]:
my_np_array = (int(), float(), str(), dict(), list(), tuple(), set(), bool()) # int, float, string, dictionary, list, tuple, set, bool 타입들을 가진 변수 생성
my_np_array = np.array([int(), float(), str(), dict(), list(), tuple(), set(), bool()], dtype=object) # Numpy 배열로 만들기
print(type(my_np_array)) # Numpy 배열이 맞는지 확인하기

# 문제 확인 (int, float, string, dictionary, list, tuple, set, bool)타입들이 잘 나오는지 확인
for i in my_np_array:
    print(type(i))

#1번 문제

<class 'numpy.ndarray'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


<h2><b>연습2:</b> 0</h2>

- <b>이 연습의 목표는 0으로 구성된 NumPy 배열을 만드는 방법을 배우는 것입니다.</b>

1. 수동으로 채우지 않고 0으로 구성된 300 차원 NumPy 배열을 만듭니다.

2. (3,100) 으로 재구성

In [3]:
np_array = np.zeros(300, dtype=int) # 배열 안에 300개의 0을 만들기
print(np_array) # 확인하기

np_array=np_array.reshape((3, 100)) # reshape(재구성)하기 1차원 -> 2차원 (100개씩 3개)
print(np_array) # 확인하기


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

<h2><b>연습3:</b> 슬라이싱</h2>

이 연습의 목표는 NumPy 인덱싱/슬라이싱을 배우는 것입니다. for 루프 없이 효율적으로 NumPy 배열의 값에 접근할 수 있습니다.

<h4>3-1</h4>
<ol>
    <li>1부터 100까지의 모든 정수를 정렬하여 포함하는 1차원 NumPy 배열을 만듭니다.</li>
    <li>for 루프를 사용하지 않고 Q1에서 만든 배열을 사용하여 모든 홀수를 포함하는 배열을 만듭니다.</li>
</ol>

In [4]:
arr = np.arange(1,100+1) # 1부터 100까지의 모든 정수를 가지는 NumPy 배열 만들기
print(arr) # 확인하기

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [5]:
arr = arr[0::2] # 슬라이싱을 사용하여 모든 홀수를 포함하는 배열을 만들기
print(arr) # 확인하기

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


<h4>3-2</h4>
<ol>
    <li>for 루프를 사용하지 않고 Q1에서 만든 배열을 사용하여, 모든 짝수 정수를 반전하여 포함하는 배열을 만듭니다.</li>
</ol>

In [6]:
arr = np.arange(1,100+1) # 100개 생성
arr = np.flip(arr[1::2]) # flip을 사용하여 반전 시키기, 슬라이싱으로 짝수 정수만 골라내기
print(arr) # 확인하기

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


<h4>3-3</h4>
<ol>
    <li>배열을 사용하여 목록의 모든 3개 요소(두 번째부터 시작) 값을 0으로 설정합니다.</li>
</ol>

In [7]:
arr = np.arange(1,100+1) # 100개 생성하기
for i in range(1, len(arr), 3): #for문으로 3칸 마다 0으로 만들기
    arr[i] = 0
print(arr) # 확인하기
#3-4

[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58   0  60  61   0  63  64   0  66  67   0  69  70   0  72
  73   0  75  76   0  78  79   0  81  82   0  84  85   0  87  88   0  90
  91   0  93  94   0  96  97   0  99 100]


<h2><b>연습4:</b> 무작위</h2>

<p>이 연습의 목표는 무작위 데이터를 생성하는 방법을 배우는 것입니다. 데이터 과학에서는 여러 가지 이유로 무작위 데이터를 생성하는 것이 매우 유용합니다. 실제 데이터 부족, 무작위 벤치마크 생성, 다양한 데이터 세트 사용 등이 있습니다. NumPy는 무작위 데이터를 생성하는 다양한 옵션을 제공합니다. 통계에서는 데이터의 분포에 대한 가정이 사용됩니다. 무작위로 생성될 수 있는 모든 데이터 분포는 설명서에 설명되어 있습니다. 이 연습에서는 두 가지 분포에 중점을 둡니다.</p>

- 균등 분포: 예를 들어, 1에서 100까지의 난수를 생성하고 모든 숫자가 같을 확률이 필요하다면 균등 분포가 필요합니다. NumPy는 균등 분포를 생성하기 위해 <code>randint</code>와 를 제공합니다.<code>uniform</code>

- 정규분포: 정규분포는 통계학에서 가장 중요한 확률 분포로, 다양한 자연 현상에 적합합니다. 예를 들어, 14세 소녀의 키를 나타내는 데이터 샘플을 생성해야 하는 경우 정규분포를 사용하여 수행할 수 있습니다. 이 경우 평균(1m51)과 표준편차(0.0741m)라는 두 가지 매개변수가 필요합니다. NumPy는 <code>randn</code>정규분포를 생성하는 데 필요한 여러 가지 기능을 제공합니다.

<h3><b>조건</b></h3>
<ol>
    <li><p>시드를 888로 설정하세요</p></li>
    <li><p>정규 분포를 따르는 크기 100의 1차원 배열을 생성합니다</p></li>
    <li><p>1~10까지의 난수 정수를 포함하는 크기가 8,8인 2차원 배열을 생성합니다(각 정수에 대해 동일한 확률)</p></li>
    <li><p>1~17까지의 난수 정수를 포함하는 크기가 4,2,5인 3차원 배열을 생성합니다(각 정수에 대해 동일한 확률)</p></li>
</ol>

In [8]:
np.random.seed(888) #시드 888로 지정 해주기

random_arr = np.random.randn(100) # randn로 정규 분표 생성
print(random_arr) #확인하기

[-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08510762e-01
 -1.40481067e+00 -6.54547

In [9]:
np.random.seed(888) #시드 888로 지정 해주기

random_arr = np.random.randint(0, 10, size = 64) #0~10까지의 난수 정수를 64(8,8) 형태로 생성
random_arr = random_arr.reshape(8,8) # reshape를 사용해서 (8,8)형태로 만들어 주기
print(random_arr) # 확인하기

[[6 3 7 9 1 0 0 9]
 [3 0 6 3 2 4 1 7]
 [2 8 6 3 8 5 9 4]
 [6 9 2 9 1 0 2 6]
 [2 1 2 1 9 8 4 3]
 [3 0 8 6 0 3 2 4]
 [2 1 9 7 5 2 8 3]
 [3 3 8 1 7 4 8 4]]


In [10]:
np.random.seed(888) #시드 888로 지정 해주기

random_arr = np.random.randint(1, 17, size = 40) #1~17까지의 난수 정수를 40(4,2,5) 형태로 생성
random_arr = random_arr.reshape(4,2,5) # reshape를 사용해서 (4, 2, 5)형태로 만들어 주기
print(random_arr) # 확인하기

[[[15 11 14 16  7]
  [ 4  8 15 10 13]]

 [[14  2  1 14 13]
  [ 1 10  4  1  7]]

 [[11  4 11  3 15]
  [15 12  5  2  8]]

 [[ 3  9  7  4 13]
  [ 9  6 10 15 11]]]


<h2><b>연습 5:</b> 배열 분할, 연결, 모양 변경하기</h2>

- 이 연습의 목표는 배열을 연결하고 재구성하는 방법을 배우는 것입니다.

1. 1~50까지의 정수를 포함하는 배열을 생성합니다.<code>array([1,...,50])</code>

2. 51에서 100까지의 정수를 포함하는 배열을 생성합니다.<code>array([51,...,100])</code>

3. 를 사용하여 <code>np.concatenate</code>두 배열을 다음과 같이 연결합니다.array([1,...,100])

4. 이전 배열을 다음과 같이 재구성합니다. (사이트 참조)

In [11]:
dom_arr = np.arange(1,51) # 1~50가지의 정수 배열 생성
print(dom_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [12]:
dom_arr2 = np.arange(51, 101) # 51~100까지의 정수 배열 생성
print(dom_arr2)

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [13]:
#np.concatenate([배열1, 배열2], axis=축번호) 형태
dom_arr_total = np.concatenate((dom_arr, dom_arr2)) # 앞에 두개의 배열 하나로 묶기 1차원은 axis생략 가능
print(dom_arr_total)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [14]:
# 재구성 하기
dom_arr_total = dom_arr_total.reshape(10,10)
print(dom_arr_total)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


<h2><b>연습 6:</b> 브로드캐스팅 및 슬라이싱</h2>

- 이 연습의 목표는 n차원 배열의 값에 효율적으로 접근하는 방법을 배우는 것입니다.

- <span style="color:red"><b>이 연습에서는 for 루프를 사용할 수 없습니다</b></span>

1. 모든 요소가 1로 초기화되고 유형이 지정된 9x9 크기의 2차원 배열을 생성합니다 <code>int8.</code>

2. 슬라이싱을 사용하여 다음 배열을 만듭니다.(사이트 참고)

3. 브로드캐스팅을 사용하여 다음 두 배열을 기반으로 출력 행렬을 생성합니다.

In [15]:
array = np.ones((9,9), dtype=np.int8) # 9,9의 이차원 배열 생성 np.int8 타입으로 생성
print(array) # 확인하기

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [16]:
array = np.ones((9,9), dtype=np.int8) # 9,9의 이차원 배열 생성 np.int8 타입으로 생성
array[1:-1] = 0 #가로
array[1:-1, [0, -1]] = 1 #세로
array[2:-2:4,2:-2] = 1 #가로
array[2:-2, [2,-3]] = 1 #세로
array[4][4] = 1 # 중간
print(array)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


<h2><b>연습 7:</b> NaN</h2>

- 이 연습의 목표는 NumPy에서 누락된 데이터를 처리하고 배열을 효과적으로 조작하는 것입니다.

- 지난 두 시험의 성적이 담긴 2차원 배열을 생각해 보겠습니다. 일부 학생이 첫 번째 시험에 결석했기 때문에 성적을 <code>NaN</code>으로 대체합니다.

- 이 시나리오를 시뮬레이션하기 위해 NumPy를 사용하여 모의 데이터셋을 생성하겠습니다. 이 데이터셋을 생성하는 코드 조각은 다음과 같습니다.

In [17]:
import numpy as np

generator = np.random.default_rng(123) # 123시드의 난수 생성 default_rng를 이용 (np.random의 업그레이드 버전)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2))) #np.round: 소수 첫째자리까지 반올림, uniform() 균등분포 난수 생성, 0~10의 10행2열 배열 생성
grades[[1,2,5,7], [0,0,0,0]] = np.nan #1,2,5,7행의 0번째 열을 nan으로 만듬
print(grades)

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [nan  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [ 8.  5.]]


- <code>np.where</code>를 사용하여 첫 번째 시험 성적이 있으면 해당 성적을 가져오는 세 번째 열을 만들고, 그렇지 않으면 두 번째 시험 성적을 사용합니다. 이 열을 배열의 세 번째 열로 추가합니다.

In [18]:
# 새 열 만들기: 조건에 따라 선택
grades2 = np.where(          # np.where(조건,x,y) 조건이 맞다면 x, 아니라면 y
    ~np.isnan(grades[:, 0]),   # 첫번째 열이 NaN이 아니라면 -> 숫자라면
    grades[:, 0],              # 첫번째 열을 사용
    grades[:, 1]               # 두번째 열을 사용
).reshape(-1, 1)               # 2차원 배열로 만듬

grades_total1 = np.concatenate([grades, grades2], axis=1) # 열 붙이기
print(grades_total1)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


<h2><b>연습 8:</b> wine</h2>

- 이 연습의 목표는 NumPy를 사용하여 실제 데이터에 대한 기본적인 데이터 분석을 수행하는 것입니다.

1. 구분 기호를 ';'로 지정하여 를 사용하여 데이터를 로드하고 <code>genfromtxt</code>, 데이터 유형을 줄여 numpy 배열 크기를 최적화합니다. 를 사용하여 <code>np.float32</code>결과 numpy 배열의 크기가 76,800바이트 인지 확인합니다 .

2. 2번째, 7번째, 12번째 행을 2차원 배열로 표시합니다. <code>np.nan</code>값이 있으면 제외합니다.

3. 데이터 세트에 알코올 도수가 20%를 넘는 와인이 있는지 확인합니다. True 또는 False를 반환합니다.

4. 데이터세트에 있는 모든 와인의 평균 알코올 도수를 계산합니다. <code>np.nan</code>값이 있으면 제외합니다.

5. 다양한 통계적 측정값(pH 값에 대한 최소값, 최대값, 25백분위수, 50백분위수, 75백분위수 및 평균)을 계산합니다.

**_참고: <code>percentile</code>또는 를 사용하면 <code>median</code>열의 중복 값에 따라 다른 결과가 나올 수 있습니다. 제 결과가 없으면 를 사용하세요 <code>percentile</code>._**

6. 황산염 함량이 20% 가장 낮은 와인의 평균 품질 점수를 찾아보세요.

7. 가장 좋은 품질의 와인에 대한 모든 변수의 평균을 계산하세요. 또한, 가장 나쁜 품질의 와인에 대해서도 같은 작업을 수행하세요.

In [89]:
# genformtxt로 wine.csv파일 가지고 오기, ;로 데이터 단위 구분, np.float32로 불러오기
data = np.genfromtxt('wine.csv' , skip_header = 0 , delimiter = ';' , dtype = np.float32)

In [20]:
print(data)
print(f"{data.nbytes} byte") # 배열의 크기 확인하기 76,800바이트 이어야 함

[[   nan    nan    nan ...    nan    nan    nan]
 [ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
76800 byte


In [21]:
np.set_printoptions(suppress=True, precision=2)  # 지수표기 끄기, 소숫점 2번째 자리까지 표기
rows = data[[2,7,12]]  # 2, 7, 12번째 행을 2차원으로 유지하며 빼내기
not_nan = np.isnan(rows).any(axis=1)  # NaN이 있는 행 찾기 true, false 반환 nan->true
clean_rows = rows[~not_nan] # NaN이 없는 행만 선택  false만 선택

print(clean_rows)

[[  7.8    0.88   0.     2.6    0.1   25.    67.     1.     3.2    0.68
    9.8    5.  ]
 [  7.9    0.6    0.06   1.6    0.07  15.    59.     1.     3.3    0.46
    9.4    5.  ]
 [  7.5    0.5    0.36   6.1    0.07  17.   102.     1.     3.35   0.8
   10.5    5.  ]]


In [22]:
#도수는 11번째 요소
#도수가 20%를 넘기면 True 그렇지 않으면 False

wine_alchol = clean_rows[:,[-2]] # 11번째 도수 부분 가지고 오기
alchol = np.any(wine_alchol > 20) # 20을 넘기면 true 그렇지 않으면 false

print(alchol) #확인하기

False


In [23]:
data_all_alchol = data[:,[-2]] #알코올 부분 모두 가지고 오기
data_all_alchol_nan = np.isnan(data_all_alchol).any(axis=1) # NaN 찾기
data_all_alchol_clean = data_all_alchol[~data_all_alchol_nan] # NaN없는 것만 골라

data_all_alchol_mean = np.mean(data_all_alchol_clean) # mean을 사용하여 평균 구하기

print(data_all_alchol_mean)

10.422984


In [24]:
#자동으로 데이터 가공해 주는 함수 만들기
def data_filter_nan(data):
    nan_find = np.isnan(data).any(axis=1)
    nan_clean = data[~nan_find]
    return nan_clean

In [25]:
# pH 값에 대한 최소값, 최대값, 25백분위수, 50백분위수, 75백분위수 및 평균 구하기
# pH는 -4번째 열
pH = data_filter_nan(data[:,[-4]]) # 함수 사용해서 pH가지고 오기
print(pH)

[[3.51]
 [3.2 ]
 [3.26]
 ...
 [3.42]
 [3.57]
 [3.39]]


In [26]:
#최솟값 min사용
pH_min = np.min(pH)
print(pH_min)

2.74


In [32]:
#최댓값 max사용
pH_max = np.max(pH)
print(pH_max)

4.01


### 백분위수란?
- 데이터를 100개의 구간으로 나눈 뒤, 그 안에서 특정 위치에 있는 값
- numpy의 <code>percentile</code>함수를 사용해서 구해보기

In [35]:
#25백분위수
pH_25 = np.percentile(pH, 25)
print(pH_25)

3.21


In [36]:
#50백분위수
pH_50 = np.percentile(pH, 50)
print(pH_50)

3.31


In [37]:
#75백분위수
pH_75 = np.percentile(pH, 75)
print(pH_75)

3.4


In [33]:
#평균구하기
pH_mean = np.mean(pH)
print(pH_mean)

3.3111134


In [ ]:
#황산염 함량이 20% 미만인 와인의 평균 품질 점수를 찾아보세요.
#sulphates는 -3번째
sulphates = data_filter_nan(data[:,[-3]]) #데이터 가공
quality = data_filter_nan(data[:,[-1]])
sul_qua = np.concatenate([sulphates, quality], axis=1) # 황산염과 퀄리티 합치기
print(sulphates)
print(quality)
print(sul_qua) # 확인

[[0.56]
 [0.68]
 [0.65]
 ...
 [0.75]
 [0.71]
 [0.66]]
[[5.]
 [5.]
 [5.]
 ...
 [6.]
 [5.]
 [6.]]
[[0.56 5.  ]
 [0.68 5.  ]
 [0.65 5.  ]
 ...
 [0.75 6.  ]
 [0.71 5.  ]
 [0.66 6.  ]]


In [ ]:
#20%미만의 값들을 찾기
sulphates_20 = np.percentile(sul_qua[:,0], 20) # 하위 20%
sulphates_20_low = sul_qua[sul_qua[:,0] <= sulphates_20] # 하위 20% 보다 작거나 같은 값 속출

print(sulphates_20_low)

[[0.56 5.  ]
 [0.68 5.  ]
 [0.65 5.  ]
 ...
 [0.54 5.  ]
 [0.58 5.  ]
 [0.71 5.  ]]


In [60]:
#와인 평균 품질 구하기
quality_low_20 = sulphates_20_low[:,1]# 20%퀄리티
quality_low_20_mean = np.mean(quality_low_20)# 평균
print(quality_low_20_mean)

4.9018817


In [65]:
#가장 좋은 품질의 와인에 대한 모든 변수의 평균을 계산하세요. 또한, 가장 나쁜 품질의 와인에 대해서도 같은 작업을 수행하세요.
#fixed acidity	volatile acidity	citric acid	residual sugar	chlorides	free sulfur dioxide	total sulfur dioxide	density	pH	sulphates	alcohol	quality의
#각 항목들의 변수를 구하기

In [72]:
all_data = data_filter_nan(data) # 모든 데이터 가지고 오기
# 가장 좋은 품질의 와인 구하기
best_quality_wine_one_data = np.max(all_data[:,-1])
best_quality_wine_all_data = all_data[all_data[:,-1] == best_quality_wine_one_data]
print(best_quality_wine_all_data)

#가장 안좋은 품질의 와인 구하기
trash_quality_wine_one_data = np.min(all_data[:,-1])
trash_quality_wine_all_data = all_data[all_data[:,-1] == trash_quality_wine_one_data]
print(trash_quality_wine_all_data)


[[ 7.9   0.35  0.46  3.6   0.08 15.   37.    1.    3.35  0.86 12.8   8.  ]
 [10.3   0.32  0.45  6.4   0.07  5.   13.    1.    3.23  0.82 12.6   8.  ]
 [ 5.6   0.85  0.05  1.4   0.05 12.   88.    0.99  3.56  0.82 12.9   8.  ]
 [12.6   0.31  0.72  2.2   0.07  6.   29.    1.    2.88  0.82  9.8   8.  ]
 [11.3   0.62  0.67  5.2   0.09  6.   19.    1.    3.22  0.69 13.4   8.  ]
 [ 9.4   0.3   0.56  2.8   0.08  6.   17.    1.    3.15  0.92 11.7   8.  ]
 [10.7   0.35  0.53  2.6   0.07  5.   16.    1.    3.15  0.65 11.    8.  ]
 [10.7   0.35  0.53  2.6   0.07  5.   16.    1.    3.15  0.65 11.    8.  ]
 [ 5.    0.42  0.24  2.    0.06 19.   50.    0.99  3.72  0.74 14.    8.  ]
 [ 7.8   0.57  0.09  2.3   0.06 34.   45.    0.99  3.46  0.74 12.7   8.  ]
 [ 9.1   0.4   0.5   1.8   0.07  7.   16.    0.99  3.21  0.69 12.5   8.  ]
 [10.    0.26  0.54  1.9   0.08 42.   74.    0.99  2.98  0.63 11.8   8.  ]
 [ 7.9   0.54  0.34  2.5   0.08  8.   17.    0.99  3.2   0.72 13.1   8.  ]
 [ 8.6   0.42  0.39  1.8 

In [71]:
#각각의 값 구하기
###
# fixed acidity	: index 0
# volatile acidity : index 1
# citric acid : index 2
# residual sugar : index 3
# chlorides : index 4
# free sulfur dioxide : index 5
# total sulfur dioxide : index 6
# density : index 7
# pH : index 8
# sulphates	: index 9
# alcohol : index 10


In [80]:
#평균을 구해주는 함수 만들기
def NumPy_mean(x, y):
    result = np.mean(x[:,[y]])
    return result

In [87]:
# 고급 와인 평균 구하기
one = NumPy_mean(best_quality_wine_all_data, 0)
two = NumPy_mean(best_quality_wine_all_data, 1)
three = NumPy_mean(best_quality_wine_all_data, 2)
four = NumPy_mean(best_quality_wine_all_data, 3)
five = NumPy_mean(best_quality_wine_all_data, 4)
six = NumPy_mean(best_quality_wine_all_data, 5)
seven = NumPy_mean(best_quality_wine_all_data, 6)
eight = NumPy_mean(best_quality_wine_all_data, 7)
nine = NumPy_mean(best_quality_wine_all_data, 8)
ten = NumPy_mean(best_quality_wine_all_data, 9)
eleven = NumPy_mean(best_quality_wine_all_data, 10)


all_list = [one, two, three, four, five, six, seven, eight, nine, ten, eleven]

for i in all_list:
    print(i)


8.566667
0.42333335
0.39111114
2.5777776
0.068444446
13.277778
33.444443
0.99521226
3.2672224
0.76777774
12.094444


In [88]:
# 꾸진 와인
one1 = NumPy_mean(trash_quality_wine_all_data, 0)
two2 = NumPy_mean(trash_quality_wine_all_data, 1)
three3 = NumPy_mean(trash_quality_wine_all_data, 2)
four4 = NumPy_mean(trash_quality_wine_all_data, 3)
five5 = NumPy_mean(trash_quality_wine_all_data, 4)
six6 = NumPy_mean(trash_quality_wine_all_data, 5)
seven7 = NumPy_mean(trash_quality_wine_all_data, 6)
eight8 = NumPy_mean(trash_quality_wine_all_data, 7)
nine9 = NumPy_mean(trash_quality_wine_all_data, 8)
ten10 = NumPy_mean(trash_quality_wine_all_data, 9)
eleven11 = NumPy_mean(trash_quality_wine_all_data, 10)

all_list2 = [one1, two2, three3, four4, five5, six6, seven7, eight8, nine9, ten10, eleven11]

for i in all_list2:
    print(i)


8.36
0.8845
0.171
2.6349998
0.12249999
11.0
24.9
0.99746406
3.398
0.57000005
9.955


<h2><b>연습 9:</b> 축구 토너먼트</h2>

- 이 연습은 순열과 복잡한 계산을 활용하는 데 중점을 둡니다.
- 귀하의 도시에서 10개 팀이 참가하는 축구 토너먼트가 진행 중입니다. 토너먼트 디렉터는 흥미진진한 1라운드를 원하며, 귀하에게 팀 편성 결정을 위임했습니다.
- 전직 데이터 과학자로서의 전문 지식을 활용하여 팀의 현재 시즌 성적을 기반으로 예측 모델을 개발했습니다. 이 모델은 두 팀 간의 점수 차이를 예측합니다.
- 모델은 다음에 저장된 2차원 배열을 생성합니다.모델 예측.txt이 행렬의 각 (i, j) 항목은 팀 i와 팀 j 간의 예상 점수 차이를 나타냅니다.
- 가장 흥미로운 경기가 펼쳐질 쌍을 결정하는 것이 목표입니다.
- 한 팀이 7-1로 이긴다면, 그 경기는 당연히 승자가 2-1로 이긴 경기보다 덜 흥미진진할 것입니다. 가장 흥미로운 경기를 만들어낼 수 있는 쌍을 찾는 기준은 차이의 제곱 합을 최소화하는 쌍 입니다.
- 예상 출력은 다음과 같습니다.

<b><span style="color:red">for 루프 사용은 허용되지 않습니다.</span> 라이브러리를 사용해야 할 수도 있습니다.itertools순열을 생성합니다.</b>

In [93]:
#model.txt 가지고 오기
data2 = np.genfromtxt('model.txt' , skip_header = 0 , delimiter = ',' , dtype = np.float32)
print(data2)

[[  nan -2.3  -4.59 -4.83  3.13  4.13  1.07  2.29  0.44  4.35]
 [ 2.3    nan  3.57 -4.66  2.3  -3.24  3.63  0.41 -2.   -0.77]
 [ 4.59 -3.57   nan  1.47  1.15 -1.16  4.97  4.81  1.86  1.5 ]
 [ 4.83  4.66 -1.47   nan  0.25 -1.9  -0.14  3.89  4.34 -1.42]
 [-3.13 -2.3  -1.15 -0.25   nan  3.9  -2.73  1.23 -4.16  3.33]
 [-4.13  3.24  1.16  1.9  -3.9    nan -0.5   2.96 -2.69 -4.48]
 [-1.07 -3.63 -4.97  0.14  2.73  0.5    nan  4.42 -1.35 -3.95]
 [-2.29 -0.41 -4.81 -3.89 -1.23 -2.96 -4.42   nan  4.49 -0.4 ]
 [-0.44  2.   -1.86 -4.34  4.16  2.69  1.35 -4.49   nan  2.29]
 [-4.35  0.77 -1.5   1.42 -3.33  4.48  3.95  0.4  -2.29   nan]]
